rntools update snapshot; the base builds

diff --git a/rntools/cppstrings b/rntools/cppstrings
--- a/rntools/cppstrings
+++ b/rntools/cppstrings
@@ -1,59 +1,153 @@
-#! /bin/sh
-################################################################################
+#!/bin/bash
 #
-# File:     cppstrings
+# File:
+#   cppstring
 #
-# Version:
-#   $LastChangedDate$
-#   $Rev$
+# Usage:
+#   cppstring [OPTION]... [FILE]
+#   cppstring --help
 #
 # Description:
-#   Print cpp built-in predefined macros and strings.
+#   Print out the C Preprocessor built-in predefined macros, strings, versions,
+#   and include paths.
 #
-# Author: Robin Knight (robin.knight@roadnarrows.com)
-#
-# Copyright (C) 2009.  RoadNarrows LLC.
-# All Rights Reserved
-#
-# Permission is hereby granted, without written agreement and without
-# license or royalty fees, to use, copy, modify, and distribute this
-# software and its documentation for any purpose, provided that
-# (1) The above copyright notice and the following two paragraphs
-# appear in all copies of the source code and (2) redistributions
-# including binaries reproduces these notices in the supporting
-# documentation.   Substantial modifications to this software may be
-# copyrighted by their authors and need not follow the licensing terms
-# described here, provided that the new terms are clearly indicated in
-# all files where they apply.
-#
-# IN NO EVENT SHALL THE AUTHOR, ROADNARROWS LLC, OR ANY MEMBERS/EMPLOYEES
-# OF ROADNARROW LLC OR DISTRIBUTORS OF THIS SOFTWARE BE LIABLE TO ANY
-# PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
-# DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
-# EVEN IF THE AUTHORS OR ANY OF THE ABOVE PARTIES HAVE BEEN ADVISED OF
-# THE POSSIBILITY OF SUCH DAMAGE.
-#
-# THE AUTHOR AND ROADNARROWS LLC SPECIFICALLY DISCLAIM ANY WARRANTIES,
-# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
-# FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN
-# "AS IS" BASIS, AND THE AUTHORS AND DISTRIBUTORS HAVE NO OBLIGATION TO
-# PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
-#
-################################################################################
 
-_Cmd="cppstrings"
+argv0=$(basename $0)
 
-cpp=cpp
+# callHelp
+callHelp()
+{
+  cat <<EOH
+Usage: ${argv0} [OPTION]... [FILE]
+       ${argv0} --help
+Print C Preprocessor built-in predefined macros and strings.
 
-if [ $# -gt 0 ]
+FILE Options:
+  -Dmacro[=defn]... 
+  -Idir...
+  -Umacro... 
+
+Options:
+  --cpp             C Preprocessor command. Default: cpp.
+  --no-color        Disable color output. Default: colors are enabled.
+
+  --help            Print this help and exit.
+
+Print out the C Preprocessor built-in predefined macros, strings, versions,
+and include paths.
+
+If FILE is specified, then cpp processes that file. Otherwise the empty file
+(/dev/null) is processed to print only the built-in envirionment. If FILE is
+specified, then most likely one or more FILE Options will be required.
+EOH
+  exit 0;
+}
+
+# ansi colors
+color_pre="\033["
+color_post="\033[0m"
+color_red="0;31m"
+color_yellow="0;33m"
+color_cyan="0;36m"
+
+# colors used
+color_warn="${color_pre}${color_yellow}"
+color_error="${color_pre}${color_red}"
+color_banner="${color_pre}${color_cyan}"
+color_end=${color_post}
+
+# showWarning wmsg [wmsg...]
+showWarning()
+{
+  printf "${argv0}: ${color_warn}${*}${color_end}\n" >&2
+}
+
+# showError emsg [emsg...]
+showError()
+{
+  printf "${argv0}: ${color_error}${*}${color_end}\n" >&2
+}
+
+# fatal exitcode emsg
+fatal()
+{
+  printf "${argv0}: ${2}\n" >&2
+  exit ${1}
+}
+
+# long and short options
+longopts="cpp:,no-color,help"
+shortopts="D:I:U:"
+
+# get the options
+OPTS=$(getopt --name ${argv0} -o "${shortopts}" --long "${longopts}" -- "${@}")
+
+if [ $? != 0 ]
 then
-  if [ "$1" = "--help" ]
-  then
-    printf "Usage: ${_Cmd} [<cppcmd>]\n"
-    exit 2
-  fi
-  cpp="$1"
+  fatal 2 "Try '${argv0} --help' for more information."
 fi
 
-${cpp} -dM -E - </dev/null
-${cpp} -v
+#echo "${OPTS}"
+eval set -- "${OPTS}"
+
+# command line option and argument variables
+cpp=cpp
+cppopts=
+srcdft=/dev/null
+
+# process command-line options
+while true
+do
+  case "$1" in
+    -D|-I|-U) cppopts="${cppopts} ${1}${2}"; shift 2;;
+    --cpp) cpp=${2}; shift 2;;
+    --no-color)
+        color_warn=
+        color_error=
+        color_banner=
+        color_end=
+        shift;;
+    --help) callHelp; shift;;
+
+    --) shift; break;;
+    *)  break;;
+  esac
+done
+
+# process command-line arguments
+src=${1:-${srcdft}}
+
+_x=$(which ${cpp})
+
+if [ -z "${_x}" ]
+then
+  fatal 4 "'${cpp}' command not found."
+fi
+
+cpp=${_x}
+
+# check cpp
+if [ ! -x "${cpp}" ]
+then
+  fatal 8 "'${cpp}' command is not an executable."
+fi
+
+bold_line='::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::' 
+
+# showBanner msg0 msg1
+showBanner()
+{
+	printf "\n\n\n${color_banner}${bold_line}\n"
+  printf ":: ${1}\n"
+  printf ":: ${2}\n"
+	printf "${bold_line}${color_end}\n\n"
+}
+
+cppopts_predef="-dM -E"
+showBanner "Predefined Macros" "${cpp} ${cppopts_predef} ${cppopts} <${src}"
+${cpp} ${cppopts_predef} ${cppopts} - <${src}
+
+cppopts_ver="-v"
+showBanner "Versions and Include Paths" \
+          "${cpp} ${cppopts_ver} ${cppopts} <${src}"
+${cpp} ${cppopts_ver} ${cppopts} - <${src}
diff --git a/rntools/rnmake_deb_all b/rntools/rnmake_deb_all
--- a/rntools/rnmake_deb_all
+++ b/rntools/rnmake_deb_all
@@ -4,12 +4,243 @@
 #   rnmake_deb_all
 #
 # Usage:
-#   rnmake_deb_all
+#   rnmake_deb_all [OPTION]... [RNMAKEVAR]... [PKG]...
+#   rnmake_deb_all --help
 #
 # Description:
-#   Make all debian development RoadNarrow SDK packages. Only packages that
-#   support debian builds will be made
+#   Make Debian packages for for all listed or discovered packages.
 #
+
+argv0=$(basename $0)
+
+# callHelp
+callHelp()
+{
+  cat <<EOH
+Usage: ${argv0} [OPTION]... [RNMAKEVAR]... [PKG]...
+       ${argv0} --help
+Make Debian packages for for all listed or discovered packages.
+
+Options:
+  --no-color        Disable color output. Default: colors are enabled.
+  --stop-on-errors  Stop on make errors. Default: warn and continue.
+  --workspace=DIR   RN package workspace directory. Default: '.'.
+
+  --help            Print this help and exit.
+
+Make Debian repo packages for all PKG packages listed on the command-line. If
+no packages are listed, then ${argv0} attempts to discover packages under
+the workspace DIR.
+
+Any command-line argument of the form name=value is considered an RNMAKEVAR 
+argument, not a PKG. All RNMAKEVAR arguments are passed to the make commands.
+EOH
+  exit 0;
+}
+
+# ansi colors
+color_pre="\033["
+color_post="\033[0m"
+color_red="0;31m"
+color_yellow="0;33m"
+color_gray="1;30m"
+
+# colors used
+color_warn="${color_pre}${color_yellow}"
+color_error="${color_pre}${color_red}"
+color_banner="${color_pre}${color_gray}"
+color_end=${color_post}
+
+# showWarning wmsg [wmsg...]
+showWarning()
+{
+  printf "${argv0}: ${color_warn}${*}${color_end}\n" >&2
+}
+
+# showError emsg [emsg...]
+showError()
+{
+  printf "${argv0}: ${color_error}${*}${color_end}\n" >&2
+}
+
+# fatal exitcode emsg
+fatal()
+{
+  printf "${argv0}: ${2}\n" >&2
+  exit ${1}
+}
+
+# long and short options
+longopts="no-color,stop-on-errors,workspace:,help"
+shortopts=""
+
+# get the options
+OPTS=$(getopt --name ${argv0} -o "${shortopts}" --long "${longopts}" -- "${@}")
+
+if [ $? != 0 ]
+then
+  fatal 2 "Try '${argv0} --help' for more information."
+fi
+
+#echo "${OPTS}"
+eval set -- "${OPTS}"
+
+# command line option and argument variables
+rnworkspace=${RNMAKE_WORKSPACE}
+stop_on_errors=false
+rnmakevars=
+pkgs=
+
+# process command-line options
+while true
+do
+  case "$1" in
+    --no-color)
+        rnmakevars="color=off"
+        color_warn=
+        color_error=
+        color_banner=
+        color_end=
+        shift;;
+    --stop-on-errors) stop_on_errors=true; shift;;
+    --workspace) rnworkspace="$2"; shift 2;;
+    --help) callHelp; shift;;
+
+    --) shift; break;;
+    *)  break;;
+  esac
+done
+
+# workspace default is current directory
+if [ -z "${rnworkspace}" ]
+then 
+  rnworkspace=.
+fi
+
+# process command-line arguments
+for arg in "${@}"
+do
+  # name=value
+  if [ "${arg%=*}" != "${arg}" ]
+  then
+    rnmakevars="${rnmakevars} ${arg}"
+   # package
+  else
+    pkgs="${pkgs} ${arg}"
+  fi
+done
+
+# no package list, so build package list from directories found under workspace
+if [ -z "${pkgs}" ]
+then
+  flist=$(ls -1 ${rnworkspace})
+  for pkg in ${flist}
+  do
+    if [ -d ${pkg} ]
+    then
+      b=$(basename ${pkg})
+      if [ "${b}" != "rntools" ]
+      then
+        pkglist="${pkglist} ${pkg}"
+      fi
+    fi
+  done
+
+  # if RNR SDK packages, sort by dependencies
+  rnrsdk=$(findShared ${0} rnrsdk.sh)
+  if [ ! -z "${rnrsdk}" ]
+  then
+    source "${rnrsdk}"
+    if rnrsdkIsGitRepo ${rnworkspace}
+    then
+      pkglist=$(rnrsdkSortByDep ${pkglist})
+    fi
+  fi
+
+# build package list from command-line packages
+else
+  for pkg in ${pkgs}
+  do
+    if [ ${pkg:0:1} = "/" ]
+    then
+      pkglist="${pkglist} ${pkg}"
+    else
+      pkglist="${pkglist} ${rnworkspace}/${pkg}"
+    fi
+  done
+fi
+
+bold_line='::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::' 
+
+# showBanner pkg
+showBanner()
+{
+	printf "\n\n\n${color_banner}${bold_line}\n"
+  printf ":: ${1}\n"
+	printf "${bold_line}${color_end}\n\n"
+}
+
+# makeIt vars tgt
+makeIt()
+{
+  if ! make "${@}"
+  then
+    if ${stop_on_errors}
+    then
+      showError "'make ${@}' failed."
+      fatal 8 "make stopped."
+    else
+      showWarning "'make ${@}' failed - continuing."
+    fi
+  fi
+}
+
+# make all packages in list
+for pkg in ${pkglist}
+do
+  deb_dev_ctl=${pkg}/make/deb-dev/control
+  deb_src_ctl=${pkg}/make/deb-src/control
+  deb_doc_ctl=${pkg}/make/deb-doc/control
+
+  if [[ ! -d ${pkg} ]]
+  then
+    showWarning "'${pkg}' is not a directory - ignoring."
+    continue
+  elif [[ ! -f ${pkg}/Makefile ]]
+  then
+    showWarning "'${pkg}/Makefile' not found - ignoring."
+    continue
+  elif [[ ( ! -f "${deb_dev_ctl}" ) && \
+          ( ! -f "${deb_src_ctl}" ) && \
+          ( ! -f "${deb_doc_ctl}" ) ]]
+  then
+    showWarning "'${pkg}/make/deb-x/control' file(s) not found - ignoring."
+    continue
+  fi
+  cd ${pkg}
+  showBanner ${pkg}
+  makeIt ${rnmakevars} clobber
+  makeIt ${rnmakevars} deps
+  makeIt ${rnmakevars} install
+  makeIt ${rnmakevars} deb-pkgs
+  cd -
+done
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
 
 pkglist='librnr libserial i2c gpio appkit peripherals netmsgs botsense Dynamixel odroid Hekateros Laelaps PanTilt Eudoxus'
 
diff --git a/rntools/rnmake_fastinstall b/rntools/rnmake_fastinstall
--- a/rntools/rnmake_fastinstall
+++ b/rntools/rnmake_fastinstall
@@ -1,7 +1,161 @@
-#!/bin/sh
+#!/bin/bash
 #
-# Fast install of SDK package. Does not install documentation.
+# File:
+#   rnmake_fastinstall
+#
+# Usage:
+#   rnmake_fastinstall [OPTION]... [RNMAKEVAR]...
+#   rnmake_fastinstall --help
+
+#   Fast install of an package.
+# Description:
+#   Fast install package. Does not install documentation.
+#   
 #
 # Usage: rnmake_fastinstall
+#
 
-make install-bin; make install-lib; make install-includes
+argv0=$(basename $0)
+
+# callHelp
+callHelp()
+{
+  cat <<EOH
+Usage: ${argv0} [OPTION]... [RNMAKEVAR]...
+       ${argv0} --help
+Fast install package. Does not install documentation.
+
+Options:
+  --no-color        Disable color output. Default: colors are enabled.
+  --stop-on-errors  Stop on make errors. Default: warn and continue.
+
+  --help            Print this help and exit.
+
+Fast install the package from the current directory. No documentation is made.
+Equivalent to 'make install-bin install-lib install-includes'.
+
+Any command-line argument is considered an RNMAKEVAR argument. All RNMAKEVAR
+arguments are passed to the make command.
+
+The ${argv0} command is useful for fast turn-around run-time
+debugging.
+
+Sit usor cave.
+EOH
+  exit 0;
+}
+
+# ansi colors
+color_pre="\033["
+color_post="\033[0m"
+color_red="0;31m"
+color_yellow="0;33m"
+color_gray="1;30m"
+
+# colors used
+color_warn="${color_pre}${color_yellow}"
+color_error="${color_pre}${color_red}"
+color_banner="${color_pre}${color_gray}"
+color_end=${color_post}
+
+# showWarning wmsg [wmsg...]
+showWarning()
+{
+  printf "${argv0}: ${color_warn}${*}${color_end}\n" >&2
+}
+
+# showError emsg [emsg...]
+showError()
+{
+  printf "${argv0}: ${color_error}${*}${color_end}\n" >&2
+}
+
+# fatal exitcode emsg
+fatal()
+{
+  printf "${argv0}: ${2}\n" >&2
+  exit ${1}
+}
+
+# long and short options
+longopts="no-color,stop-on-errors,help"
+shortopts=""
+
+# get the options
+OPTS=$(getopt --name ${argv0} -o "${shortopts}" --long "${longopts}" -- "${@}")
+
+if [ $? != 0 ]
+then
+  fatal 2 "Try '${argv0} --help' for more information."
+fi
+
+#echo "${OPTS}"
+eval set -- "${OPTS}"
+
+# command line option and argument variables
+stop_on_errors=false
+rnmakevars=
+pkg=$(realpath .)
+
+# process command-line options
+while true
+do
+  case "$1" in
+    --no-color)
+        rnmakevars="color=off"
+        color_warn=
+        color_error=
+        color_banner=
+        color_end=
+        shift;;
+    --stop-on-errors) stop_on_errors=true; shift;;
+    --help) callHelp; shift;;
+
+    --) shift; break;;
+    *)  break;;
+  esac
+done
+
+# process command-line arguments
+rnmakevars="${rnmakevars} ${@}"
+
+bold_line='::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::-::' 
+
+# showBanner pkg
+showBanner()
+{
+	printf "\n${color_banner}${bold_line}\n"
+  printf ":: ${1}\n"
+	printf "${bold_line}${color_end}\n\n"
+}
+
+# makeIt vars tgt
+makeIt()
+{
+  if ! make "${@}"
+  then
+    if ${stop_on_errors}
+    then
+      showError "'make ${@}' failed."
+      fatal 8 "make stopped."
+    else
+      showWarning "'make ${@}' failed - continuing."
+    fi
+  fi
+}
+
+# package checks
+if [[ ! -d ${pkg} ]]
+then
+    showWarning "'${pkg}' is not a directory - ignoring."
+    continue
+elif [[ ! -f ${pkg}/Makefile ]]
+then
+    showWarning "'${pkg}/Makefile' not found - ignoring."
+    continue
+fi
+
+showBanner ${pkg}
+
+# make
+makeIt ${rnmakevars} install-bin install-lib install-includes
