tested rn tools

diff --git a/rntools/rnmake_fastinstall b/rntools/rnmake_fastinstall
--- a/rntools/rnmake_fastinstall
+++ b/rntools/rnmake_fastinstall
@@ -46,14 +46,35 @@ EOH
 color_pre="\033["
 color_post="\033[0m"
 color_red="0;31m"
+color_bold_red="1;31m"
+color_green="0;32m"
 color_yellow="0;33m"
 color_gray="1;30m"
 
 # colors used
+color_info="${color_pre}${color_green}"
 color_warn="${color_pre}${color_yellow}"
 color_error="${color_pre}${color_red}"
+color_fatal="${color_pre}${color_bold_red}"
 color_banner="${color_pre}${color_gray}"
 color_end=${color_post}
+
+# turnOffColor
+turnOffColor()
+{
+  color_info=
+  color_warn=
+  color_error=
+  color_fatal=
+  color_banner=
+  color_end=
+}
+
+# showInfo msg [msg...]
+showInfo()
+{
+  printf "${color_info}${*}${color_end}\n"
+}
 
 # showWarning wmsg [wmsg...]
 showWarning()
@@ -70,9 +91,10 @@ showError()
 # fatal exitcode emsg
 fatal()
 {
-  printf "${argv0}: ${2}\n" >&2
+  printf "${argv0}: ${color_fatal}${2}${color_end}\n" >&2
   exit ${1}
 }
+
 
 # long and short options
 longopts="no-color,stop-on-errors,help"
@@ -99,11 +121,8 @@ while true
 do
   case "$1" in
     --no-color)
+        turnOffColor
         rnmakevars="color=off"
-        color_warn=
-        color_error=
-        color_banner=
-        color_end=
         shift;;
     --stop-on-errors) stop_on_errors=true; shift;;
     --help) callHelp; shift;;
@@ -144,12 +163,10 @@ makeIt()
 # package checks
 if [[ ! -d ${pkg} ]]
 then
-    showWarning "'${pkg}' is not a directory - ignoring."
-    continue
+    fatal 8 "'${pkg}' is not a directory."
 elif [[ ! -f ${pkg}/Makefile ]]
 then
-    showWarning "'${pkg}/Makefile' not found - ignoring."
-    continue
+    fatal 8 "'${pkg}/Makefile' not found."
 fi
 
 showBanner ${pkg}
